name: EpicPunish
version: 1.0
main: com.gmail.justbru00.epic.punish.main.Main
authors: [Justin Brubaker, JustBru00]
commands:
  epicpunish:
    description: A basic version command.
  punish:
    desctiption: Command used for punishing players.        